### ISSUE TITLE
issue with shader

### ISSUE THREAD

**Issue by DigitalMonkeyPa1** [Zylann/godot_heightmap_native_plugin#46] opened 2018-07-05 18:01 UTC
When a scene with HTerrain is run, debugger shows the following error:
Invalid call. Nonexistent function 'set_shader_param' in base 'Nil'.
	(In stack)
	0 - res://addons/zylann.hterrain/detail/detail_renderer.gd:247
	1 - res://addons/zylann.hterrain/detail/hterrain.gd:648

**Comment by Zylann** [comment] 2018-07-05 18:48
Which are the reproduction steps you did for this to happen? I'm not getting this error when running the demo.

**Comment by DigitalMonkeyPa1** [comment] 2018-07-19 18:32
Sorry for the delay, the demo works fine for me too, and today there is no error, but wind is not working, the grass just bends once(based on wind param) and stays there.

Sometimes, when the project is opened up all the textures are missing, sometimes only grass textures are missing.

Sometimes I get one of the following errors for multiple times, infinitely till the editor is closed:
-DetailLayer processing while there are no layers!
-DetailLayer processing while terrain is null!

Grass does not appear instantly when the project is reopened:
When the project is reopened, terrain appears with the splat, but grass is not shown until Hterrain node is selected in the inspector(since the terrain does not get selected by mouse clicks, the node has to be clicked).

Sorry for putting a lot of content, I don't know how and where these errors occur

**Comment by Zylann** [comment] 2018-07-19 19:17
In the editor, level of detail doesn't work well because the plugin can only access the camera when it receives events, so that means only when the terrain is selected. You will notice geometry quality won't update if it's not selected.

About the other issues, do they happen as you do things to the terrain, or just randomly while you open the project *and do no modifications to it*? If you do any change and get an error, I would like to know what steps.

**Comment by Zylann** [comment] 2018-08-03 00:53
I am getting it too but it's hard to tell why it happens.

**Comment by DigitalMonkeyPa1** [comment] 2018-08-03 16:56
also grass gets culled away even at some moderate distance, it's so hard while painting grass since I can't see the grass until I get close to the location, also the zooming in and out is not so friendly in godot editor.
Is there a way to change the cull distance for grass, if possible while editing (ie: when editor_hint == true) let the cull distance be high, in game it can be lowered on wish, ie: having two cull distances will be nice.

**Comment by Zylann** [comment] 2018-08-03 17:20
The culling bug is already reported in #35

**Comment by Zylann** [comment] 2018-08-03 19:59
Fixed in b0143b5d970bf7ddfc73e25d3c2c991a2c73b5d1, let me know if it happens again

**Closed** 2018-08-08 19:52 UTC
Labels: bug
