### ISSUE TITLE
Collision not working

### ISSUE THREAD

**Issue by MmTtDeveloper** [Zylann/godot_heightmap_native_plugin#24] opened 2018-04-15 15:11 UTC
The collision does not seem to work. I tried it in the demo and it didn't work their either.

**Comment by Zylann** [comment] 2018-04-15 15:34
Duplicate of https://github.com/Zylann/godot_heightmap_native_plugin/issues/9
It doesn't work in Godot 3.0.2, but I think it will in 3.0.3.

**Closed by Zylann** 2018-04-15 15:34 UTC

**Comment by Zylann** [comment] 2018-04-16 14:19
@MmTtDeveloper no, it's a bug in the engine I fixed after 3.0.2, so it should work in 3.0.3
